### ISSUE TITLE
[Design] Set space between items in main screen

### ISSUE THREAD

**Issue by overeha** [code4romania/ro-help#111]
- [x] Please set the spaces between elements like this
- [x] do not forget about the line above useful instruments (grey line aligned to title bottom)
 
![space](https://user-images.githubusercontent.com/45068169/77705170-a70c5600-6fc7-11ea-94b0-e243aa79868e.JPG)

**Comment by iulianstana** [comment]
I will do this

**Comment by acis** [comment]
@iulianstana  e la mine, aprope gata

**Comment by iulianstana** [comment]
ok :D
