### ISSUE TITLE
Add social og tags 

### ISSUE THREAD

**Issue by costibleotu** [code4romania/ro-help#117]
Tags:
- [ ] og:url
- [ ] og:type = website
- [ ] og:title (the title of the page. In case of a need form will be the title of the need ) 
- [ ] og:description
- [ ] og:image

Tags should be added in `base.html` templates and overwritten in individual pages as NGO need, NGO Detail, NGO Registration, etc

To test  the implementation you can access this [link](https://developers.facebook.com/tools/debug/)

**Comment by alex-muntean** [comment]
Iau eu asta
