### ISSUE TITLE
Missing role link for https://www.aadr.ro from top of main page http://dev.rohelp.ro/ro/

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#120]
Starting point: http://dev.rohelp.ro/ro/

**Expected**: 
Click on role img Autoritatea pentru digitalizarea României 
Autoritatea pentru digitalizarea României site opens https://www.aadr.ro

**Actual**: 
Guvernul României site opens https://www.gov.ro 

**Steps performed/Reproduction**: 
Click on role img Autoritatea pentru digitalizarea României 
![Screenshot 2020-03-28 at 12 22 03](https://user-images.githubusercontent.com/61550276/77821051-b8508200-70ef-11ea-8fee-2e85a4f6a2ac.png)

**Comment by iulianstana** [comment]
I will take this one

**Comment by DragomirStefanaCatalina** [comment]
Missing role link for https://www.gov.ro from top of the main page http://dev.rohelp.ro/ro/

**Expected**:
Click on role img Guvernul României
Guvernul României site opens https://www.gov.ro

**Actual**:
Click on role img Guvernul României
Autoritatea pentru digitalizarea României site opens https://www.aadr.ro

@iulianstana @costibleotu

**Comment by iulianstana** [comment]
I am a bit confused here... the aadr.ro icon includes the gov.ro icon. Do you think that both icons should work in a different way?

<img width="444" alt="Screenshot 2020-03-28 at 18 04 22" src="https://user-images.githubusercontent.com/1146100/77827510-a89c6200-711e-11ea-9f51-82303c3962fe.png">

**Comment by DragomirStefanaCatalina** [comment]
Both icons should have two different role img with two different role links: https://www.gov.ro & https://www.aadr.ro :)
