### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#130]
1.	‘Despre proiect’ link redirects to Page not found 
2.	‘Ce trebuie sa fac’ link redirects to stirioficiale.ro
3.	Politica de confidentialitate is inactive
4.	Regulament is inactive

**Comment by catileptic** [comment]
@overeha can you help us settle on the links in the footer?

**Comment by overeha** [comment]
Please see Issue #94

**Comment by catileptic** [comment]
Done. Closing this.

**Comment by gepaltineanu** [comment]
Cookie policy cannot be accessed, it redirects to an exception page:

Exception Type:  TemplateDoesNotExist
Exception Value: cookies.html
