### ISSUE TITLE
Header issues

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#131]
1. Despre, Regulament and Contact sections are empty. 
2. Hungarian language is not supported, it displays the page in Romanian.

**Comment by catileptic** [comment]
We'll try our best to roll out the HU translation in v1 but there's a chance it will come afterwards. 

As for the pages, @overeha can you help us with the content?

**Comment by overeha** [comment]
Revin pe rand cu ele: 
Regulament here:

[Reguli RoHelp.docx](https://github.com/code4romania/ro-help/files/4407924/Reguli.RoHelp.docx)

**Comment by overeha** [comment]
**Contact section:** 

Text:
**TITLE:**
Contactează-ne

**TEXT:** 
RoHelp este o platformă de management de ajutoare dezvoltată de Asociația Code for România în parteneriat cu Guvernul României prin Autoritatea pentru Digitalizarea României și administrată de Code for Romania.

RoHelp centralizează asociațiile și fundațiile care lucrează activ pentru ameliorarea crizei generate de epidemia COVID-19, oferindu-le acestora acces la o platformă în care pot colecta resursele financiare și materiale necesare în acest scop (e.g. sume de bani, ajutoare materiale, muncă prestată de voluntari etc).

Dacă întâmpini orice dificultate tehnică, te rugăm să ne transmiți un mesaj pe adresa contact@code4.ro.

**Comment by catileptic** [comment]
Done. closing this.

**Comment by gepaltineanu** [comment]
It seems that "How to" section is still empty
