### ISSUE TITLE
Sidebar issues

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#132]
None of the buttons on the sidebar are active.

**Comment by AlecsGherghel** [comment]
@costibleotu Do we want the sidebar buttons/sections to look similar to what's on https://stirioficiale.ro/ ?

If so, I can take care of that.

**Comment by vtemian** [comment]
I think those should look similar.

**Comment by AlecsGherghel** [comment]
@vtemian gotcha. imma take care of this then.
