### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#133]
Although the search function works when hitting Enter button, the ‘magnifying glass’ logo should also act as a button.

**Comment by xeeo** [comment]
Is this the version from dev.rohelp.ro ? because in the repo (develop branch) the search bar is already different.

**Comment by gepaltineanu** [comment]
Yes:
http://dev.rohelp.ro/ro/

**Comment by xeeo** [comment]
In the repo there is another search bar that is functional :)

**Comment by AlecsGherghel** [comment]
Ill pick this one

**Comment by AlecsGherghel** [comment]
Ok, someone with more FE exp can pick this one up. It kills me to align a submit button instead of the <span> element with magnifying glass :-D

**Comment by tudorgergely** [comment]
I'll take this
