### ISSUE TITLE
Donation not possible yet

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#134]
Not possible to make donation to NGOs, after filling the details in the form the user is redirected to an 'Exception' page.
Also, ‘TODO: add a success message’ is shown.

**Comment by costibleotu** [comment]
It should only work for [Code4](http://dev.rohelp.ro/ro/ngos/1088/19368/?kind=money)  (is the only one having a mobilpay account)
To test a donation use one of the cards [here](https://suport.mobilpay.ro/index.php?/Knowledgebase/Article/View/57/12/carduri-de-test)

**Comment by gepaltineanu** [comment]
Even for Code4, I still get the same behavior

**Comment by costibleotu** [comment]
We have a problem with the storage on AWS right now so we are losing the credential at each build. We'll check this after we fix the storage.

**Comment by costibleotu** [comment]
It was not working because the storage was not working. Test it now

**Comment by gepaltineanu** [comment]
It worked fine now. Tested for Code4.
