### ISSUE TITLE
Suggestion for accessing NGO's details

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#135]
Suggestion: at the moment the only way to access more details about the NGOs is to click the Donate/I can help buttons. Suggestion is to also allow the user to access the NGO’s details by clicking on its name or on its image, while maintaining the Donate/I can help buttons available for users that want to access directly the donation/help pages for that NGO.

**Comment by costibleotu** [comment]
I agree and thought about this.
@overeha what do you say?

**Comment by AlecsGherghel** [comment]
@costibleotu I think we can add another button with _NGO Details_ underneath the current one and make it link to the NGO detail view.

We can also add an hyperlink on NGO image/name

I don't think we'd break design if we'd do something like this:

<img width="866" alt="Screenshot 2020-03-29 at 12 59 38" src="https://user-images.githubusercontent.com/12795061/77846240-4e061300-71bd-11ea-8bb1-76cd653d43e3.png">

**Comment by AlecsGherghel** [comment]
Ill pick this one

**Comment by costibleotu** [comment]
We need input from @overeha.

**Comment by overeha** [comment]
Hello, sorry for lag in reply. 
Thank you for the suggestion. The question is very valid, however I will have to say no in regards to the design proposed. Normally this would be very useful, but it defeats the centerpiece action. Having two call to actions (2 buttons) with the same weight in the same location will decrease considerably the probability for the user to perform any of the actions. 

If we want to provide the user with the possibility to access the NGO description then we should make the NGO name clickable, but not design it as an option as heavyweight as the Donation (our main purpose) button.

**Comment by catileptic** [comment]
Closing this, thank you for the input @overeha!

**Comment by gepaltineanu** [comment]
I can confirm that the NGO name is now clickable and this takes the user to the NGO's details.
My suggestion would be to also add the Donate button here, in the details section. In my opinion, after the user goes through the details and decides to make a donation, it is easier for him/her to directly click Donate here. Current situation is: the user has to go back to access the Donate button after going through the NGO description.
