### ISSUE TITLE
Filters for county/city suggestion

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#136]
Filters: when filtering for the county, the filter for the cities should update itself to show only cities within that county. Or if you filter directly by city, the county filter should automatically change to that city’s county.
At the moment it is possible for example to filter:
county: Arad
city: Bucuresti

**Comment by adriangabrieloros** [comment]
I can take this.

**Comment by vtemian** [comment]
For now, the filters work like this: when you select a county, the filter for city is populated with cities from that county. If you select a city, the county filter doesn't reset. The urgency filter takes into account both city and county filter.

https://github.com/code4romania/ro-help/blob/develop/ro_help/hub/views.py#L158

The staging area is a little bit too random and indeed can generate some weird behavior like county Arad and city Bucuresti.

https://github.com/code4romania/ro-help/blob/develop/ro_help/hub/management/commands/seed.py#L101

I don't see any of the above described as bugs or undesired behaviors. What do you think?

**Comment by adriangabrieloros** [comment]
You are right. We'll trust the ONGs to properly insert the data for now. Let's skip this task and focus on the more urgent ones.

**Comment by catileptic** [comment]
Closing this, for now.
