### ISSUE TITLE
No confirmation for 'I can help' action

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ro-help#139]
For both ‘I can help with resources’ and ‘I want to volunteer’, after submitting the details the following message is shown: TODO: add a success message. Also there is no email sent to the user.

**Comment by costibleotu** [comment]
We decided to not send any email to the user in this situation. Should we reconsider this, @catileptic @overeha ?

**Comment by catileptic** [comment]
We stick to the decision not to send an e-mail to the user. We will reconsider this if it proves that it's an inappropriate flow, but, thus far, it seems reasonable that a success message is enough. The NGO will contact the user by phone/email to coordinate. Closing this.
