### ISSUE TITLE
[Content] About page

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#14]
Create content for the About page.

The content should cover:
* what RO Help is
* the main use cases for this platform (asking for help as an NGO, asking for help as a citizen and directing your request to an NGO)
* how to offer and ask for help - general guidelines (make your requests atomic and specific, create one request per resource need, and one request per city)
* good practices for NGOs and citizens (close their own requests when they have been fulfilled, close the requests made by citizens once the NGO has fulfilled them)

**Comment by mgeox** [comment]
I will handle this.

**Comment by catileptic** [comment]
@overeha can you help us with this?

**Comment by overeha** [comment]
Regulament

[Reguli RoHelp.docx](https://github.com/code4romania/ro-help/files/4407900/Reguli.RoHelp.docx)

**Comment by overeha** [comment]
About page. Let us just leave it like this for now. I hope I will have a prettier text by tomorrow at noon. 

RoHelp este o platformă de management de ajutoare dezvoltată de Asociația Code for România în parteneriat cu Guvernul României prin Autoritatea pentru Digitalizarea României și administrată de Code for Romania.

RoHelp centralizează asociațiile și fundațiile care lucrează activ pentru ameliorarea crizei generate de epidemia COVID-19, oferindu-le acestora acces la o platformă în care pot colecta resursele financiare și materiale necesare în acest scop (e.g. sume de bani, ajutoare materiale, muncă prestată de voluntari etc).

Resursele financiare sunt colectate de asociațiile și fundațiile înscrise în Platformă în mod direct, prin intermediul contului alocat acestora, pe baza unui contract încheiat cu operatorul de plăți Netopia.

**Comment by catileptic** [comment]
Done, closing this
