### ISSUE TITLE
Change Password operation reads old password as new password 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#142]
Starting point: http://dev.rohelp.ro/en/admin/auth/user/6/change/

**Expected**:
Error message: 

> Please correct the error below. Your new password must be different. Please try again. 

or

> Please correct the error below. Invalid new password. Please try again. 

**Actual**:

> Your password was changed. Password change successful.

**Steps performed/Reproduction:**
Trying to Change Password
1. Click on Change Password button from right corner 
http://dev.rohelp.ro/en/admin/auth/user/6/change/
2. Password change page opens
http://dev.rohelp.ro/en/admin/password_change/
![Screenshot 2020-03-28 at 14 14 19](https://user-images.githubusercontent.com/61550276/77822785-8d215f00-70fe-11ea-98b3-3f43a2b04fce.png)
3. Type the current password in all 3 fields corresponding to old password, new password & new password confirmation 
4. Click on Change Password button request
http://dev.rohelp.ro/en/admin/password_change/done/
![Screenshot 2020-03-28 at 14 13 40](https://user-images.githubusercontent.com/61550276/77822868-39fbdc00-70ff-11ea-92e7-01007f7abe21.png)

**Comment by AlecsGherghel** [comment]
I can take this
