### ISSUE TITLE
NGO bank accounts are hardcoded in the template

### ISSUE THREAD

**Issue by andrei1089** [code4romania/ro-help#145]
<p>Nume: Asociația Habitat for Humanity</p>
                        <p>Sediu: Piata Unirii 16,Bucuresti</p>
                        <p>CIF: RO22556447</p>
                        <p>CUI: 323265</p>

                        <p>Cont RON: RO38BTRLRONCRT0505050505</p>
                        <p>Cont EUR: RO38BTRLRONCRT0505050505</p>
                        <p>Cont USD: RO38BTRLRONCRT0505050505</p>

                        <p>Banca: Raiffeisen Bank</p>

**Comment by AlecsGherghel** [comment]
@vtemian @catileptic I assume this information should come from the NGO model (or through the NGO model).

If so, I can pick it up and make this editable rather than hardcoded.

**Comment by andrei1089** [comment]
@AlecsGherghel it's already handled by https://github.com/code4romania/ro-help/pull/157
