### ISSUE TITLE
Suggestion - add sort options

### ISSUE THREAD

**Issue by ionitadaniel19** [code4romania/ro-help#158]
You only have filters now for NGOs. 
Also when selecting a filter the displayed results are not ordered ascending by alphabetical order.

**Comment by cosmin-bianu** [comment]
I can work on this

**Comment by catileptic** [comment]
The NGO needs should not be sorted in alphabetical order, they should be ordered by Urgency.

The filters in Ro Help are applied to NGO needs, not NGOs. 

Closing this.
