### ISSUE TITLE
Missing role link for https://www.gov.ro from top of the main page http://dev.rohelp.ro/ro/

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#161]
**Expected**:
Click on role img Guvernul României
Guvernul României site opens https://www.gov.ro

**Actual**:
Click on role img Guvernul României
Autoritatea pentru digitalizarea României site opens https://www.aadr.ro

![Screenshot 2020-03-28 at 18 01 12](https://user-images.githubusercontent.com/61550276/77827435-4e9b9c80-711e-11ea-99f2-8cb4ec538c7c.png)

_Originally posted by @DragomirStefanaCatalina in https://github.com/code4romania/ro-help/issues/120#issuecomment-605466467_

**Comment by AlecsGherghel** [comment]
That's because "Guvernul Romaniei" logo and AADR logo are one and the same image.

If there are independent logos for this 2 entities we can easily fix this.

**Comment by DragomirStefanaCatalina** [comment]
https://github.com/code4romania/ro-help/issues/120#issuecomment-605487675
