### ISSUE TITLE
Suggestion: Sendgrid for emails

### ISSUE THREAD

**Issue by AlecsGherghel** [code4romania/ro-help#173]
I've noticed that we're using local SMTP for emails. I suspect that we might encounter issues due to DKIM configuration which might lead to emails being sent to spam.

Sendgrid has a free plan which allows us to send 100 emails / day which should be more than enough to cover the needs for NGO registrations.

As long as we get a set of API keys should be fairly simple to integrate.

**Comment by vtemian** [comment]
In staging, we're using AWS SES. We should be safe, right @AlecsGherghel ?

**Comment by AlecsGherghel** [comment]
@vtemian Yup. That's definitely better. Wasn't aware of this so we can close this one.
