### ISSUE TITLE
Donating button for Crucea Rosie doesn't do anything.

### ISSUE THREAD

**Issue by adriangabrieloros** [code4romania/ro-help#176]
The button on the main page located in the red banner on the main page does not do anything.
It should take you to a donation form.

**Comment by adriangabrieloros** [comment]
I'll start working on this.

**Comment by costibleotu** [comment]
The link should go to the "Red Cross" donations page. Which means we need a way to inject the url of that need (`NgoNeed`: `name=Crucea Rosie`, `kind=money`)

**Comment by catileptic** [comment]
Closed by #199
