### ISSUE TITLE
Design logo for Facebook sharing - new format needed

### ISSUE THREAD

**Issue by alex-muntean** [code4romania/ro-help#178]
Here are the 2 references that I've found for best practices:
[https://developers.facebook.com/docs/sharing/best-practices/](https://developers.facebook.com/docs/sharing/best-practices/)
[https://developers.facebook.com/docs/sharing/webmasters#markup](https://developers.facebook.com/docs/sharing/webmasters#markup)

**Extras:**
The minimum allowed image dimension is 200 x 200 pixels.
The size of the image file must not exceed 8 MB.
Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images.

The format of the picture should be jpeg.

Generated by issue: [https://github.com/code4romania/ro-help/issues/117](https://github.com/code4romania/ro-help/issues/117)

**Comment by catileptic** [comment]
Fixed by [this](https://github.com/code4romania/ro-help/commit/0e36120e173cb7a16c95f023f5d0689f609c88cb). Closing this Issue.
