### ISSUE TITLE
Adding multiple tags to an NGO need multiplies the need object

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#179]
**Steps to recreate:**
1. Log into the admin panel as a user that has an NGO
2. Create a need
3. Attach two pre-existing tags to the need
4. Search for the need in the needs listing
5. You will notice there are two identical needs, same title, same tags
6. Add one more tags
7. Refresh the listing
8. There are now three identical needs

**Comment by AlecsGherghel** [comment]
Picking this

**Comment by vtemian** [comment]
I guess we need a `.distinct()` for the queryset result?
