### ISSUE TITLE
Missing search bar for NGO pending requests & NGO register requests

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#185]
Starting point: http://dev.rohelp.ro/en/admin/hub/pendingregisterngorequest/
http://dev.rohelp.ro/en/admin/hub/registerngorequest/

**Expected**:
Search bar for 
> NGO pending requests
> NGO register requests 

from Hub menu on the right side of the page as in 

>NGO Needs
>NGO report items
>NGOs 
>Resource tags 

submenus
for operability, consistency & uniformity

![Screenshot 2020-03-30 at 22 50 01](https://user-images.githubusercontent.com/61550276/77955431-dcbb8280-72d8-11ea-8252-4aed4187d6ce.png)

**Actual**:
Missing search bar for 

> NGO pending requests 
> NGO register requests

![Screenshot 2020-03-30 at 22 20 14](https://user-images.githubusercontent.com/61550276/77953797-4dad6b00-72d6-11ea-98f3-8a92d5b69a27.png)

![Screenshot 2020-03-30 at 22 25 17](https://user-images.githubusercontent.com/61550276/77953778-48502080-72d6-11ea-9123-366d0c6c0e0f.png)

**Comment by catileptic** [comment]
Clsoed by #189
