### ISSUE TITLE
Add admin panel button

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#195]
Add a link to `/admin` as a button in the nav bar that should only be visible if a user is logged in.

**Comment by AlecsGherghel** [comment]
@catileptic I can pick this. Do we want to display the admin button for **all** logged in users or should we _worry_ about permissions and stuff?

**Comment by costibleotu** [comment]
I would say that we should display it for all logged users.

**Comment by AlecsGherghel** [comment]
Sounds good. It works like this already in the current PR.
