### ISSUE TITLE
'Forgotten your password or username' does not send any email 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#208]
Starting point: http://dev.rohelp.ro/en/admin/login/?next=/en/admin/

**Expected**:
Receiving an email in Inbox/Junk/Spam with the relevant instructions in order to change the forgotten password when clicked on

> Forgotten your password or username?

**Actual**:
No email in Inbox/Junk/Spam with the relevant instructions in order to change the forgotten password 

**Steps performed/Reproduction**:
1. Click on

> Forgotten your password or username?

![Screenshot 2020-03-31 at 19 30 27](https://user-images.githubusercontent.com/61550276/78062327-32566480-7397-11ea-97c6-293f0ae68439.png)

2. Password reset page opens

![Screenshot 2020-03-31 at 19 29 49](https://user-images.githubusercontent.com/61550276/78062373-4601cb00-7397-11ea-9df0-d48927b3a1a4.png)

3. Enter your email address 

4. Click on Reset my password button 
5. Password reset sent page opens
![Screenshot 2020-03-31 at 19 30 55](https://user-images.githubusercontent.com/61550276/78062384-4ac67f00-7397-11ea-9176-168beb726dfa.png)

6. No email in Inbox/Junk/Spam received

**Comment by AlecsGherghel** [comment]
im going to take a look over this
