### ISSUE TITLE
Add tag filter

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#213]
Including the tags in the search algorithm proved to be a complicated problem to solve and, after much back and forth, we decided it's not worth solving. The search feature is supposed to give the user a helping hand in finding a NGO or a certain need title. 

In order to address the tags, we decided to add them as filters. 
Just like we have a filter for City, County and Urgency, let's add one which will list all the tags, and a check box next to each of them. A user can therefore check multiple tags and this will filter the Needs list. The desired effect is to only display the needs which contain the selected tags among their tags.

**Comment by AlecsGherghel** [comment]
@catileptic I can take this and probably get it either tonight or tomorrow morning.
