### ISSUE TITLE
Selecting a need type should highlight the filter box

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#214]
This used to be a feature but it somehow got lost. 

When a need type is selected, the box is supposed to change color, as per the image below. 

![image](https://user-images.githubusercontent.com/14028425/78144594-7a799380-7438-11ea-9a56-5691c32f265e.png)

**Comment by catileptic** [comment]
@adriangabrieloros is on this

**Comment by adriangabrieloros** [comment]
https://github.com/code4romania/ro-help/pull/223
