### ISSUE TITLE
No confirmation email for new NGO added

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#217]
Starting point: http://dev.rohelp.ro/en/admin/hub/ngo/

**Expected**:
Receiving an email in Inbox/Junk/Spam with the confirmation that the NGO was added successfully

**Actual**:
No email in Inbox/Junk/Spam with the confirmation that the NGO was added successfully

**Comment by catileptic** [comment]
It is unclear to me _who_ should receive the e-mail. 

If an Administrator adds an NGO, there is no point in sending an e-mail to the Administrator.

On the other hand, if your point is that the e-mail address assigned to the NGO should receive an e-mail saying that the NGO was created, this is an improvement we could add.

**Comment by cristina0botez** [comment]
I think @DragomirStefanaCatalina was expecting the 2nd scenario to happen. I can work on it.

**Comment by catileptic** [comment]
The design decision is to not send an e-mail when an NGO is added, but rather when it is activated. At the moment, the mail is sent when an NGO is activated. Closing this.
