### ISSUE TITLE
No rule for Resource tag name

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#219]
Starting point: http://dev.rohelp.ro/en/admin/hub/resourcetag/

**Expected**:
When adding a resource tag, the name field should accept characters together with digits, punctuation marks & symbols 

**Actual**:
When adding a resource tag, the name field accepts digits only, punctuation marks only or symbols only

![Screenshot 2020-04-01 at 17 39 01](https://user-images.githubusercontent.com/61550276/78150710-54f08800-7440-11ea-8e3a-4cd2c68687d4.png)

**Comment by costibleotu** [comment]
I will add a rule for valid tag consisting of letters, numbers, hyphens, coma or spaces. No symbols.

**Comment by catileptic** [comment]
Fixed by #233
