### ISSUE TITLE
Admin panel display issues

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#220]
There are several tweaks that the admin panel could use, in terms of the display of various pieces of text.

[RO] Cerere înregistrare ONG
<img width="713" alt="Screenshot 2020-04-01 at 19 15 08" src="https://user-images.githubusercontent.com/14028425/78160788-1d3c0d00-744d-11ea-9317-8d84a1e94f04.png">

[EN] NGO Register Request
<img width="720" alt="Screenshot 2020-04-01 at 19 15 48" src="https://user-images.githubusercontent.com/14028425/78160848-347afa80-744d-11ea-9b1b-4fb1c635af44.png">

[RO] Caută ceree de înregistrare ONG în așteptare
<img width="246" alt="Screenshot 2020-04-01 at 20 04 29" src="https://user-images.githubusercontent.com/14028425/78165460-05b45280-7454-11ea-8ec0-8eb153960900.png">

[EN] Search NGO pending request
<img width="247" alt="Screenshot 2020-04-01 at 20 03 41" src="https://user-images.githubusercontent.com/14028425/78165369-e6b5c080-7453-11ea-8aaa-af8e463ffb13.png">

In all views where the NGO details are read-only, the following items overlap:
<img width="339" alt="Screenshot 2020-04-01 at 20 36 06" src="https://user-images.githubusercontent.com/14028425/78168334-6c3b6f80-7458-11ea-9cf8-480fc14b24db.png">

**Comment by costibleotu** [comment]
I fixed all but the tables.
