### ISSUE TITLE
AttributeError for Payment responses submenu from Mobilpay menu

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#225]
Starting point: http://dev.rohelp.ro/en/admin/

**Expected**:
Payment responses submenu from Mobilpay menu opens in same tab after simple click

**Actual**:
Payment responses submenu from Mobilpay menu opens in same tab after simple click displaying an AttributeError

![Screenshot 2020-04-02 at 20 28 57](https://user-images.githubusercontent.com/61550276/78279719-a4a68080-7520-11ea-8950-200a8e7a7b3c.png)

http://dev.rohelp.ro/en/admin/mobilpay/paymentresponse/

**Steps performed/Reproduction**:
1. Click on Mobilpay menu
2. Select Payment responses

![Screenshot 2020-04-02 at 20 20 55](https://user-images.githubusercontent.com/61550276/78279454-3366cd80-7520-11ea-881e-27ff419502ca.png)

3. AttributeError page opens

**Comment by catileptic** [comment]
Fixed by #233
