### ISSUE TITLE
Add NGO pending request link is broken

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#231]
In the admin panel, the "Add NGO pending request" link (on the button in the bottom-right corner) is broken.

[See here](http://dev.rohelp.ro/en/admin/hub/pendingregisterngorequest/add/)

**Comment by costibleotu** [comment]
I fixed the error, but I disabled the possibility of adding a pending request. If an admin wants to manually create an ngo request, it will create one from `/ro/admin/hub/registerngorequest/` . Pending is just a proxy where you see the requests you did not vote for

**Comment by catileptic** [comment]
This is a very fair decision. I completely agree.
