### ISSUE TITLE
Scroll enhancement

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#252]
- [ ] When a user clicks on the "I can help" button they are redirected to the NGO page. Here, they should land on the need, inside the carousel. Currently, they land at the top of the page. 
- [ ] When a user clicks on the "Donate" button in the Netopia need, they are redirected to the NEtopia form page. Here, they should land on the top part of the form. Currently, they land at the top of the page.

**Comment by AlecsGherghel** [comment]
I pick this
