### ISSUE TITLE
[Content edit] Add link and remove text in Contact page

### ISSUE THREAD

**Issue by overeha** [code4romania/ro-help#330]
Here in the first paragraph. 

delete "(insert link)"
add [this link](https://rohelp.ro/ro/ngos/register) on "platforma aici"
![image](https://user-images.githubusercontent.com/45068169/79210929-3336ce00-7e4e-11ea-85ec-66c890657342.png)

**Comment by catileptic** [comment]
Taking this

**Comment by catileptic** [comment]
[Fixed by this commit](https://github.com/code4romania/ro-help/commit/24d64693a741552584a118d0a6933653eae54bea)
