### ISSUE TITLE
Filters container is breaking the page layout on mobile

### ISSUE THREAD

**Issue by cipick** [code4romania/ro-help#332]
<img width="348" alt="Screenshot 2020-04-14 at 14 08 11" src="https://user-images.githubusercontent.com/6429818/79218729-8f531f80-7e59-11ea-8e61-3d2187a67ddf.png">

**Comment by catileptic** [comment]
Fixed by [this commit](https://github.com/code4romania/ro-help/commit/04736b461ba7ec5e385858ef6975365d8eba93fd). Closing.
