### ISSUE TITLE
In the City drop down there are two options for Iasi

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ro-help#350]
1. Open https://rohelp.ro/ro/?county=IASI&city=Ia%C8%99i&urgency=medium
2. Hover over the City dropdown

Expected results: There should be only one option for Iasi

Actual results: 
![orase](https://user-images.githubusercontent.com/6797637/79924438-75f53900-8440-11ea-9bf2-2b5dd1d22a85.png)

**Comment by catileptic** [comment]
Fixed. Closing.
