### ISSUE TITLE
Unbalanced NGO list

### ISSUE THREAD

**Issue by lcapatina** [code4romania/ro-help#356]
On the main page [main page](https://rohelp.ro/en/?page=1&kind=money) of the NGO list (no filtering applied) there is an infinite scroll for the first page displaying 51 NGOs and at the end, we only have the last button even though we are on page 1 out of 6.
It seems that the first page loads the data for the 5 first pages.
![unbalanced_list_p1_screenshot](https://user-images.githubusercontent.com/7313937/80229237-6c422000-8650-11ea-97f2-461e21245145.PNG)

Same behavior if we go on page 3: all the NGOs from page 3 to 5 included are loaded and next button is missing.
![unbalanced_list_p3_screenshot](https://user-images.githubusercontent.com/7313937/80229665-0bffae00-8651-11ea-8961-566124539620.PNG)

**Comment by catileptic** [comment]
The needs list now has an infinite scroll feature, so this is no longer an Issue.
If you find this faulty behaviour elsewhere in the website, please open a new Issue. :)
