### ISSUE TITLE
Add Back to Top Button

### ISSUE THREAD

**Issue by catileptic** [code4romania/ro-help#357]
Now that the needs listing page has infinite scroll, we need a Back to top Button. 

The button needs to rest just above the footer when the maximum scroll depth has been reached. 
An implementation of the back to top button, for reference, can be found in the Taskforce React components, [here](https://github.com/code4romania/taskforce-fe-components/tree/master/src/components/back-to-top). 

RoHelp does not have React on the frontend, so the button will have to be implemented from scratch.

**Comment by stevefai** [comment]
I'll take this one
